In [1]:
import requests
from bs4 import BeautifulSoup as bs

In [2]:
# 실제 사이트에서 html 정보를 받아와서 변수에 저장
data = requests.get('https://finance.naver.com/marketindex/exchangeList.naver').text

In [3]:
# BeautifulSoup을 이용하여 데이터를 파싱
soup = bs(data, 'html.parser')

In [4]:
print(soup)

<html lang="ko">
<head>
<title>네이버 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20230531104931/css/finance.css" rel="stylesheet" type="text/css"/>
<script language="javascript">document.domain="naver.com";</script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230531104931/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20230531104931/js/lcslog.js" type="text/javascript"></script>
</head>
<body>
<div class="tbl_area">
<table border="1" class="tbl_exchange" summary="환전 고시 환율 리스트">
<caption>환전 고시 환율</caption>
<colgroup>
<col width="162"/>
<col width="92"/>
<col width="92"/>
<col width="92"/>
<col width="93"/>
<col width="92"/>
<col width="90"/>
</colgroup>
<thead>
<tr>
<th class="th_ex1" rowspan="2">
<a href="#" onclick="javascript:changeOrder('exchange'); return false;"><span>통화명</span></a></th>
<th class="th_ex2" rowspan="2"><span>매매기준율</span></th>
<th class="th_ex3" colspan="2"><span>현찰</span></th>
<th class="th_ex4" colspan="2"><span>송금</span></th>
<th class="th_ex6" rowspan="2"><span>미화환산율</span></th>
</tr>
<tr>
<th class="th_ex7"><span>사실 때 </span></th>
<th class="th_ex8"><span>파실 때 </span></th>
<th class="th_ex9"><span>보내실 때 </span></th>
<th class="th_ex10"><span>받으실 때</span></th>
</tr>
</thead>
<tbody>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_USDKRW', '1', event);" target="_parent">




					미국 USD

				</a></td>
<td class="sale">1,277.00</td>
<td>


						1,299.34

				</td>
<td>


						1,254.66

				</td>
<td>


						1,289.50

				</td>
<td>


						1,264.50

				</td>
<td>1.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EURKRW', '2', event);" target="_parent">




					유럽연합 EUR

				</a></td>
<td class="sale">1,390.27</td>
<td>


						1,417.93

				</td>
<td>


						1,362.61

				</td>
<td>


						1,404.17

				</td>
<td>


						1,376.37

				</td>
<td>1.089</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JPYKRW', '3', event);" target="_parent">

					일본 JPY (100엔)




				</a></td>
<td class="sale">908.54</td>
<td>


						924.43

				</td>
<td>


						892.65

				</td>
<td>


						917.44

				</td>
<td>


						899.64

				</td>
<td>0.712</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CNYKRW', '4', event);" target="_parent">




					중국 CNY

				</a></td>
<td class="sale">178.79</td>
<td>


						187.72

				</td>
<td>


						169.86

				</td>
<td>


						180.57

				</td>
<td>


						177.01

				</td>
<td>0.140</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HKDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HKDKRW', '5', event);" target="_parent">




					홍콩 HKD

				</a></td>
<td class="sale">163.22</td>
<td>


						166.43

				</td>
<td>


						160.01

				</td>
<td>


						164.85

				</td>
<td>


						161.59

				</td>
<td>0.128</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TWDKRW', '6', event);" target="_parent">




					대만 TWD

				</a></td>
<td class="sale">41.56</td>
<td>


						47.00

				</td>
<td>


						37.41

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.033</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_GBPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_GBPKRW', '7', event);" target="_parent">




					영국 GBP

				</a></td>
<td class="sale">1,621.15</td>
<td>


						1,653.08

				</td>
<td>


						1,589.22

				</td>
<td>


						1,637.36

				</td>
<td>


						1,604.94

				</td>
<td>1.270</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_OMRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_OMRKRW', '8', event);" target="_parent">




					오만 OMR

				</a></td>
<td class="sale">3,316.88</td>
<td>


						3,549.06

				</td>
<td>


						3,084.70

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>2.597</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CADKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CADKRW', '9', event);" target="_parent">




					캐나다 CAD

				</a></td>
<td class="sale">960.29</td>
<td>


						979.20

				</td>
<td>


						941.38

				</td>
<td>


						969.89

				</td>
<td>


						950.69

				</td>
<td>0.752</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CHFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CHFKRW', '10', event);" target="_parent">




					스위스 CHF

				</a></td>
<td class="sale">1,423.79</td>
<td>


						1,451.83

				</td>
<td>


						1,395.75

				</td>
<td>


						1,438.02

				</td>
<td>


						1,409.56

				</td>
<td>1.115</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SEKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SEKKRW', '11', event);" target="_parent">




					스웨덴 SEK

				</a></td>
<td class="sale">119.87</td>
<td>


						122.80

				</td>
<td>


						116.94

				</td>
<td>


						121.06

				</td>
<td>


						118.68

				</td>
<td>0.094</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AUDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AUDKRW', '12', event);" target="_parent">




					호주 AUD

				</a></td>
<td class="sale">873.02</td>
<td>


						890.21

				</td>
<td>


						855.83

				</td>
<td>


						881.75

				</td>
<td>


						864.29

				</td>
<td>0.684</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NZDKRW', '13', event);" target="_parent">




					뉴질랜드 NZD

				</a></td>
<td class="sale">791.87</td>
<td>


						807.46

				</td>
<td>


						776.28

				</td>
<td>


						799.78

				</td>
<td>


						783.96

				</td>
<td>0.620</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CZKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CZKKRW', '14', event);" target="_parent">




					체코 CZK

				</a></td>
<td class="sale">58.48</td>
<td>


						63.45

				</td>
<td>


						53.22

				</td>
<td>


						59.12

				</td>
<td>


						57.84

				</td>
<td>0.046</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CLPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_CLPKRW', '15', event);" target="_parent">




					칠레 CLP

				</a></td>
<td class="sale">1.60</td>
<td>


						1.76

				</td>
<td>


						1.44

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.001</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_TRYKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_TRYKRW', '16', event);" target="_parent">




					튀르키예 TRY

				</a></td>
<td class="sale">53.96</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>


						54.55

				</td>
<td>


						53.37

				</td>
<td>0.042</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MNTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MNTKRW', '17', event);" target="_parent">




					몽골 MNT

				</a></td>
<td class="sale">0.37</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ILSKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ILSKRW', '18', event);" target="_parent">




					이스라엘 ILS

				</a></td>
<td class="sale">358.36</td>
<td>


						394.19

				</td>
<td>


						329.70

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.281</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DKKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DKKKRW', '19', event);" target="_parent">




					덴마크 DKK

				</a></td>
<td class="sale">186.58</td>
<td>


						191.15

				</td>
<td>


						182.01

				</td>
<td>


						188.44

				</td>
<td>


						184.72

				</td>
<td>0.146</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_NOKKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_NOKKRW', '20', event);" target="_parent">




					노르웨이 NOK

				</a></td>
<td class="sale">121.42</td>
<td>


						124.39

				</td>
<td>


						118.45

				</td>
<td>


						122.63

				</td>
<td>


						120.21

				</td>
<td>0.095</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SARKRW', '21', event);" target="_parent">




					사우디아라비아 SAR

				</a></td>
<td class="sale">340.52</td>
<td>


						361.97

				</td>
<td>


						317.03

				</td>
<td>


						343.92

				</td>
<td>


						337.12

				</td>
<td>0.267</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KWDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KWDKRW', '22', event);" target="_parent">




					쿠웨이트 KWD

				</a></td>
<td class="sale">4,159.47</td>
<td>


						4,429.83

				</td>
<td>


						3,826.72

				</td>
<td>


						4,201.06

				</td>
<td>


						4,117.88

				</td>
<td>3.257</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BHDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BHDKRW', '23', event);" target="_parent">




					바레인 BHD

				</a></td>
<td class="sale">3,387.27</td>
<td>


						3,604.05

				</td>
<td>


						3,116.29

				</td>
<td>


						3,421.14

				</td>
<td>


						3,353.40

				</td>
<td>2.653</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_AEDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_AEDKRW', '24', event);" target="_parent">




					아랍에미리트 AED

				</a></td>
<td class="sale">347.68</td>
<td>


						366.80

				</td>
<td>


						323.70

				</td>
<td>


						351.15

				</td>
<td>


						344.21

				</td>
<td>0.272</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JODKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_JODKRW', '25', event);" target="_parent">




					요르단 JOD

				</a></td>
<td class="sale">1,800.11</td>
<td>


						1,960.31

				</td>
<td>


						1,656.11

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>1.410</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EGPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_EGPKRW', '26', event);" target="_parent">




					이집트 EGP

				</a></td>
<td class="sale">41.33</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.032</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_THBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_THBKRW', '27', event);" target="_parent">




					태국 THB

				</a></td>
<td class="sale">36.78</td>
<td>


						38.61

				</td>
<td>


						34.58

				</td>
<td>


						37.14

				</td>
<td>


						36.42

				</td>
<td>0.029</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_SGDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_SGDKRW', '28', event);" target="_parent">




					싱가포르 SGD

				</a></td>
<td class="sale">953.87</td>
<td>


						972.85

				</td>
<td>


						934.89

				</td>
<td>


						963.40

				</td>
<td>


						944.34

				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MYRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MYRKRW', '29', event);" target="_parent">




					말레이시아 MYR

				</a></td>
<td class="sale">276.05</td>
<td>


						296.47

				</td>
<td>


						255.63

				</td>
<td>

						N/A


				</td>
<td>


						273.29

				</td>
<td>0.216</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_IDRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_IDRKRW', '30', event);" target="_parent">


					인도네시아 IDR 100



				</a></td>
<td class="sale">8.56</td>
<td>


						9.41

				</td>
<td>


						7.71

				</td>
<td>


						8.64

				</td>
<td>


						8.48

				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_QARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_QARKRW', '31', event);" target="_parent">




					카타르 QAR

				</a></td>
<td class="sale">350.32</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.274</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KZTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KZTKRW', '32', event);" target="_parent">




					카자흐스탄 KZT

				</a></td>
<td class="sale">2.82</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.002</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BNDKRW', '33', event);" target="_parent">




					브루나이 BND

				</a></td>
<td class="sale">953.87</td>
<td>


						992.02

				</td>
<td>


						896.64

				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.747</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_INRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_INRKRW', '34', event);" target="_parent">




					인도 INR

				</a></td>
<td class="sale">15.57</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PKRKRW', '35', event);" target="_parent">




					파키스탄 PKR

				</a></td>
<td class="sale">4.45</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BDTKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BDTKRW', '36', event);" target="_parent">




					방글라데시 BDT

				</a></td>
<td class="sale">11.80</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.009</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PHPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PHPKRW', '37', event);" target="_parent">




					필리핀 PHP

				</a></td>
<td class="sale">22.86</td>
<td>


						25.14

				</td>
<td>


						20.99

				</td>
<td>


						23.08

				</td>
<td>


						22.64

				</td>
<td>0.018</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_MXNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_MXNKRW', '38', event);" target="_parent">




					멕시코 MXN

				</a></td>
<td class="sale">74.39</td>
<td>


						82.20

				</td>
<td>


						66.58

				</td>
<td>


						75.13

				</td>
<td>


						73.65

				</td>
<td>0.058</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_BRLKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_BRLKRW', '39', event);" target="_parent">




					브라질 BRL

				</a></td>
<td class="sale">264.85</td>
<td>


						291.86

				</td>
<td>


						238.37

				</td>
<td>

						N/A


				</td>
<td>


						261.68

				</td>
<td>0.207</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_VNDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_VNDKRW', '40', event);" target="_parent">



					베트남 VND 100


				</a></td>
<td class="sale">5.43</td>
<td>


						6.07

				</td>
<td>


						4.79

				</td>
<td>


						5.48

				</td>
<td>


						5.38

				</td>
<td>0.004</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_ZARKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_ZARKRW', '41', event);" target="_parent">




					남아프리카 공화국 ZAR

				</a></td>
<td class="sale">69.66</td>
<td>


						75.23

				</td>
<td>


						64.09

				</td>
<td>


						70.49

				</td>
<td>


						68.83

				</td>
<td>0.055</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_RUBKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_RUBKRW', '42', event);" target="_parent">




					러시아 RUB

				</a></td>
<td class="sale">15.26</td>
<td>


						16.70

				</td>
<td>


						12.59

				</td>
<td>


						15.79

				</td>
<td>


						14.73

				</td>
<td>0.012</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_HUFKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_HUFKRW', '43', event);" target="_parent">




					헝가리 HUF

				</a></td>
<td class="sale">3.71</td>
<td>


						4.05

				</td>
<td>


						3.42

				</td>
<td>


						3.75

				</td>
<td>


						3.67

				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_PLNKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_PLNKRW', '44', event);" target="_parent">




					폴란드 PLN

				</a></td>
<td class="sale">311.32</td>
<td>


						336.22

				</td>
<td>


						286.42

				</td>
<td>


						314.74

				</td>
<td>


						307.90

				</td>
<td>0.244</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_LKRKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_LKRKRW', '45', event);" target="_parent">




					스리랑카 LKR

				</a></td>
<td class="sale">4.17</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.003</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_DZDKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_DZDKRW', '46', event);" target="_parent">




					알제리 DZD

				</a></td>
<td class="sale">9.41</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_KESKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_KESKRW', '47', event);" target="_parent">




					케냐 KES

				</a></td>
<td class="sale">9.13</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.007</td>
</tr>
<tr>
<td class="tit"><a href="/marketindex/exchangeDetail.naver?marketindexCd=FX_COPKRW" onclick="parent.clickcr(this, 'exl.exlist', 'FX_COPKRW', '48', event);" target="_parent">




					콜롬비아 COP

				</a></td>
<td class="sale">0.31</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>

						N/A


				</td>
<td>0.000</td>
</tr>
<tr>

In [5]:
# find는 html안에서 해당 태그의 첫 번째 정보를 출력
tbody = soup.find('tbody')

In [6]:
# find_all() 해당 태그의 전체 정보를 리스트의 형태로 출력
data_list = soup.find_all('td')

In [7]:
# data_list를 이용하여 2차원 배열로 새로운 리스트를 생성
# 1차원 리스트 생성
# [[7개씩], [7개씩], [7개씩], [7개씩]] -> 2차원 리스트
_list = []
for i in data_list:
    x = i.get_text()
    x = x.replace("\n", '')
    x = x.strip("\t")
    _list.append(x)
_list

['미국 USD',
 '1,277.00',
 '1,299.34',
 '1,254.66',
 '1,289.50',
 '1,264.50',
 '1.000',
 '유럽연합 EUR',
 '1,390.27',
 '1,417.93',
 '1,362.61',
 '1,404.17',
 '1,376.37',
 '1.089',
 '일본 JPY (100엔)',
 '908.54',
 '924.43',
 '892.65',
 '917.44',
 '899.64',
 '0.712',
 '중국 CNY',
 '178.79',
 '187.72',
 '169.86',
 '180.57',
 '177.01',
 '0.140',
 '홍콩 HKD',
 '163.22',
 '166.43',
 '160.01',
 '164.85',
 '161.59',
 '0.128',
 '대만 TWD',
 '41.56',
 '47.00',
 '37.41',
 'N/A',
 'N/A',
 '0.033',
 '영국 GBP',
 '1,621.15',
 '1,653.08',
 '1,589.22',
 '1,637.36',
 '1,604.94',
 '1.270',
 '오만 OMR',
 '3,316.88',
 '3,549.06',
 '3,084.70',
 'N/A',
 'N/A',
 '2.597',
 '캐나다 CAD',
 '960.29',
 '979.20',
 '941.38',
 '969.89',
 '950.69',
 '0.752',
 '스위스 CHF',
 '1,423.79',
 '1,451.83',
 '1,395.75',
 '1,438.02',
 '1,409.56',
 '1.115',
 '스웨덴 SEK',
 '119.87',
 '122.80',
 '116.94',
 '121.06',
 '118.68',
 '0.094',
 '호주 AUD',
 '873.02',
 '890.21',
 '855.83',
 '881.75',
 '864.29',
 '0.684',
 '뉴질랜드 NZD',
 '791.87',
 '807.46',
 '776.28',
 '799.78',
 '783.96',
 '0.620',
 '체코 CZK',
 '58.48',
 '63.45',
 '53.22',
 '59.12',
 '57.84',
 '0.046',
 '칠레 CLP',
 '1.60',
 '1.76',
 '1.44',
 'N/A',
 'N/A',
 '0.001',
 '튀르키예 TRY',
 '53.96',
 'N/A',
 'N/A',
 '54.55',
 '53.37',
 '0.042',
 '몽골 MNT',
 '0.37',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '이스라엘 ILS',
 '358.36',
 '394.19',
 '329.70',
 'N/A',
 'N/A',
 '0.281',
 '덴마크 DKK',
 '186.58',
 '191.15',
 '182.01',
 '188.44',
 '184.72',
 '0.146',
 '노르웨이 NOK',
 '121.42',
 '124.39',
 '118.45',
 '122.63',
 '120.21',
 '0.095',
 '사우디아라비아 SAR',
 '340.52',
 '361.97',
 '317.03',
 '343.92',
 '337.12',
 '0.267',
 '쿠웨이트 KWD',
 '4,159.47',
 '4,429.83',
 '3,826.72',
 '4,201.06',
 '4,117.88',
 '3.257',
 '바레인 BHD',
 '3,387.27',
 '3,604.05',
 '3,116.29',
 '3,421.14',
 '3,353.40',
 '2.653',
 '아랍에미리트 AED',
 '347.68',
 '366.80',
 '323.70',
 '351.15',
 '344.21',
 '0.272',
 '요르단 JOD',
 '1,800.11',
 '1,960.31',
 '1,656.11',
 'N/A',
 'N/A',
 '1.410',
 '이집트 EGP',
 '41.33',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.032',
 '태국 THB',
 '36.78',
 '38.61',
 '34.58',
 '37.14',
 '36.42',
 '0.029',
 '싱가포르 SGD',
 '953.87',
 '972.85',
 '934.89',
 '963.40',
 '944.34',
 '0.747',
 '말레이시아 MYR',
 '276.05',
 '296.47',
 '255.63',
 'N/A',
 '273.29',
 '0.216',
 '인도네시아 IDR 100',
 '8.56',
 '9.41',
 '7.71',
 '8.64',
 '8.48',
 '0.007',
 '카타르 QAR',
 '350.32',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.274',
 '카자흐스탄 KZT',
 '2.82',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.002',
 '브루나이 BND',
 '953.87',
 '992.02',
 '896.64',
 'N/A',
 'N/A',
 '0.747',
 '인도 INR',
 '15.57',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.012',
 '파키스탄 PKR',
 '4.45',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.004',
 '방글라데시 BDT',
 '11.80',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.009',
 '필리핀 PHP',
 '22.86',
 '25.14',
 '20.99',
 '23.08',
 '22.64',
 '0.018',
 '멕시코 MXN',
 '74.39',
 '82.20',
 '66.58',
 '75.13',
 '73.65',
 '0.058',
 '브라질 BRL',
 '264.85',
 '291.86',
 '238.37',
 'N/A',
 '261.68',
 '0.207',
 '베트남 VND 100',
 '5.43',
 '6.07',
 '4.79',
 '5.48',
 '5.38',
 '0.004',
 '남아프리카 공화국 ZAR',
 '69.66',
 '75.23',
 '64.09',
 '70.49',
 '68.83',
 '0.055',
 '러시아 RUB',
 '15.26',
 '16.70',
 '12.59',
 '15.79',
 '14.73',
 '0.012',
 '헝가리 HUF',
 '3.71',
 '4.05',
 '3.42',
 '3.75',
 '3.67',
 '0.003',
 '폴란드 PLN',
 '311.32',
 '336.22',
 '286.42',
 '314.74',
 '307.90',
 '0.244',
 '스리랑카 LKR',
 '4.17',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.003',
 '알제리 DZD',
 '9.41',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '케냐 KES',
 '9.13',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.007',
 '콜롬비아 COP',
 '0.31',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '탄자니아 TZS',
 '0.53',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '네팔 NPR',
 '9.71',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.008',
 '루마니아 RON',
 '280.19',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.219',
 '리비아 LYD',
 '265.31',
 'N/A',
 'N/A',
 '267.96',
 '262.66',
 '0.208',
 '마카오 MOP',
 '158.19',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.124',
 '미얀마 MMK',
 '0.61',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.001',
 '에티오피아 ETB',
 '23.25',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.018',
 '우즈베키스탄 UZS',
 '0.11',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '캄보디아 KHR',
 '0.31',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.000',
 '피지 FJD',
 '579.18',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '0.454']

In [8]:
len(_list) // 7

58

In [9]:
result = []
for i in range(0, (len(_list)//7), 1):
    x = []
    for j in range(i*7, (i+1)*7, 1):
        x.append(_list[j])
    result.append(x)
result

[['미국 USD',
  '1,277.00',
  '1,299.34',
  '1,254.66',
  '1,289.50',
  '1,264.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,390.27',
  '1,417.93',
  '1,362.61',
  '1,404.17',
  '1,376.37',
  '1.089'],
 ['일본 JPY (100엔)', '908.54', '924.43', '892.65', '917.44', '899.64', '0.712'],
 ['중국 CNY', '178.79', '187.72', '169.86', '180.57', '177.01', '0.140'],
 ['홍콩 HKD', '163.22', '166.43', '160.01', '164.85', '161.59', '0.128'],
 ['대만 TWD', '41.56', '47.00', '37.41', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,621.15',
  '1,653.08',
  '1,589.22',
  '1,637.36',
  '1,604.94',
  '1.270'],
 ['오만 OMR', '3,316.88', '3,549.06', '3,084.70', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '960.29', '979.20', '941.38', '969.89', '950.69', '0.752'],
 ['스위스 CHF',
  '1,423.79',
  '1,451.83',
  '1,395.75',
  '1,438.02',
  '1,409.56',
  '1.115'],
 ['스웨덴 SEK', '119.87', '122.80', '116.94', '121.06', '118.68', '0.094'],
 ['호주 AUD', '873.02', '890.21', '855.83', '881.75', '864.29', '0.684'],
 ['뉴질랜드 NZD', '791.87', '807.46', '776.28', '799.78', '783.96', '0.620'],
 ['체코 CZK', '58.48', '63.45', '53.22', '59.12', '57.84', '0.046'],
 ['칠레 CLP', '1.60', '1.76', '1.44', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '53.96', 'N/A', 'N/A', '54.55', '53.37', '0.042'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '358.36', '394.19', '329.70', 'N/A', 'N/A', '0.281'],
 ['덴마크 DKK', '186.58', '191.15', '182.01', '188.44', '184.72', '0.146'],
 ['노르웨이 NOK', '121.42', '124.39', '118.45', '122.63', '120.21', '0.095'],
 ['사우디아라비아 SAR', '340.52', '361.97', '317.03', '343.92', '337.12', '0.267'],
 ['쿠웨이트 KWD',
  '4,159.47',
  '4,429.83',
  '3,826.72',
  '4,201.06',
  '4,117.88',
  '3.257'],
 ['바레인 BHD',
  '3,387.27',
  '3,604.05',
  '3,116.29',
  '3,421.14',
  '3,353.40',
  '2.653'],
 ['아랍에미리트 AED', '347.68', '366.80', '323.70', '351.15', '344.21', '0.272'],
 ['요르단 JOD', '1,800.11', '1,960.31', '1,656.11', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '41.33', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '36.78', '38.61', '34.58', '37.14', '36.42', '0.029'],
 ['싱가포르 SGD', '953.87', '972.85', '934.89', '963.40', '944.34', '0.747'],
 ['말레이시아 MYR', '276.05', '296.47', '255.63', 'N/A', '273.29', '0.216'],
 ['인도네시아 IDR 100', '8.56', '9.41', '7.71', '8.64', '8.48', '0.007'],
 ['카타르 QAR', '350.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.82', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '953.87', '992.02', '896.64', 'N/A', 'N/A', '0.747'],
 ['인도 INR', '15.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.45', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '11.80', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '22.86', '25.14', '20.99', '23.08', '22.64', '0.018'],
 ['멕시코 MXN', '74.39', '82.20', '66.58', '75.13', '73.65', '0.058'],
 ['브라질 BRL', '264.85', '291.86', '238.37', 'N/A', '261.68', '0.207'],
 ['베트남 VND 100', '5.43', '6.07', '4.79', '5.48', '5.38', '0.004'],
 ['남아프리카 공화국 ZAR', '69.66', '75.23', '64.09', '70.49', '68.83', '0.055'],
 ['러시아 RUB', '15.26', '16.70', '12.59', '15.79', '14.73', '0.012'],
 ['헝가리 HUF', '3.71', '4.05', '3.42', '3.75', '3.67', '0.003'],
 ['폴란드 PLN', '311.32', '336.22', '286.42', '314.74', '307.90', '0.244'],
 ['스리랑카 LKR', '4.17', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.41', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.13', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.31', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.53', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '9.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '280.19', 'N/A', 'N/A', 'N/A', 'N/A', '0.219'],
 ['리비아 LYD', '265.31', 'N/A', 'N/A', '267.96', '262.66', '0.208'],
 ['마카오 MOP', '158.19', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '23.25', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.31', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '579.18', 'N/A', 'N/A', 'N/A', 'N/A', '0.454']]

In [10]:
result = []
for i in range(len(_list)//7):
    result.append(_list[i*7:(i+1)*7])
result

[['미국 USD',
  '1,277.00',
  '1,299.34',
  '1,254.66',
  '1,289.50',
  '1,264.50',
  '1.000'],
 ['유럽연합 EUR',
  '1,390.27',
  '1,417.93',
  '1,362.61',
  '1,404.17',
  '1,376.37',
  '1.089'],
 ['일본 JPY (100엔)', '908.54', '924.43', '892.65', '917.44', '899.64', '0.712'],
 ['중국 CNY', '178.79', '187.72', '169.86', '180.57', '177.01', '0.140'],
 ['홍콩 HKD', '163.22', '166.43', '160.01', '164.85', '161.59', '0.128'],
 ['대만 TWD', '41.56', '47.00', '37.41', 'N/A', 'N/A', '0.033'],
 ['영국 GBP',
  '1,621.15',
  '1,653.08',
  '1,589.22',
  '1,637.36',
  '1,604.94',
  '1.270'],
 ['오만 OMR', '3,316.88', '3,549.06', '3,084.70', 'N/A', 'N/A', '2.597'],
 ['캐나다 CAD', '960.29', '979.20', '941.38', '969.89', '950.69', '0.752'],
 ['스위스 CHF',
  '1,423.79',
  '1,451.83',
  '1,395.75',
  '1,438.02',
  '1,409.56',
  '1.115'],
 ['스웨덴 SEK', '119.87', '122.80', '116.94', '121.06', '118.68', '0.094'],
 ['호주 AUD', '873.02', '890.21', '855.83', '881.75', '864.29', '0.684'],
 ['뉴질랜드 NZD', '791.87', '807.46', '776.28', '799.78', '783.96', '0.620'],
 ['체코 CZK', '58.48', '63.45', '53.22', '59.12', '57.84', '0.046'],
 ['칠레 CLP', '1.60', '1.76', '1.44', 'N/A', 'N/A', '0.001'],
 ['튀르키예 TRY', '53.96', 'N/A', 'N/A', '54.55', '53.37', '0.042'],
 ['몽골 MNT', '0.37', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['이스라엘 ILS', '358.36', '394.19', '329.70', 'N/A', 'N/A', '0.281'],
 ['덴마크 DKK', '186.58', '191.15', '182.01', '188.44', '184.72', '0.146'],
 ['노르웨이 NOK', '121.42', '124.39', '118.45', '122.63', '120.21', '0.095'],
 ['사우디아라비아 SAR', '340.52', '361.97', '317.03', '343.92', '337.12', '0.267'],
 ['쿠웨이트 KWD',
  '4,159.47',
  '4,429.83',
  '3,826.72',
  '4,201.06',
  '4,117.88',
  '3.257'],
 ['바레인 BHD',
  '3,387.27',
  '3,604.05',
  '3,116.29',
  '3,421.14',
  '3,353.40',
  '2.653'],
 ['아랍에미리트 AED', '347.68', '366.80', '323.70', '351.15', '344.21', '0.272'],
 ['요르단 JOD', '1,800.11', '1,960.31', '1,656.11', 'N/A', 'N/A', '1.410'],
 ['이집트 EGP', '41.33', 'N/A', 'N/A', 'N/A', 'N/A', '0.032'],
 ['태국 THB', '36.78', '38.61', '34.58', '37.14', '36.42', '0.029'],
 ['싱가포르 SGD', '953.87', '972.85', '934.89', '963.40', '944.34', '0.747'],
 ['말레이시아 MYR', '276.05', '296.47', '255.63', 'N/A', '273.29', '0.216'],
 ['인도네시아 IDR 100', '8.56', '9.41', '7.71', '8.64', '8.48', '0.007'],
 ['카타르 QAR', '350.32', 'N/A', 'N/A', 'N/A', 'N/A', '0.274'],
 ['카자흐스탄 KZT', '2.82', 'N/A', 'N/A', 'N/A', 'N/A', '0.002'],
 ['브루나이 BND', '953.87', '992.02', '896.64', 'N/A', 'N/A', '0.747'],
 ['인도 INR', '15.57', 'N/A', 'N/A', 'N/A', 'N/A', '0.012'],
 ['파키스탄 PKR', '4.45', 'N/A', 'N/A', 'N/A', 'N/A', '0.004'],
 ['방글라데시 BDT', '11.80', 'N/A', 'N/A', 'N/A', 'N/A', '0.009'],
 ['필리핀 PHP', '22.86', '25.14', '20.99', '23.08', '22.64', '0.018'],
 ['멕시코 MXN', '74.39', '82.20', '66.58', '75.13', '73.65', '0.058'],
 ['브라질 BRL', '264.85', '291.86', '238.37', 'N/A', '261.68', '0.207'],
 ['베트남 VND 100', '5.43', '6.07', '4.79', '5.48', '5.38', '0.004'],
 ['남아프리카 공화국 ZAR', '69.66', '75.23', '64.09', '70.49', '68.83', '0.055'],
 ['러시아 RUB', '15.26', '16.70', '12.59', '15.79', '14.73', '0.012'],
 ['헝가리 HUF', '3.71', '4.05', '3.42', '3.75', '3.67', '0.003'],
 ['폴란드 PLN', '311.32', '336.22', '286.42', '314.74', '307.90', '0.244'],
 ['스리랑카 LKR', '4.17', 'N/A', 'N/A', 'N/A', 'N/A', '0.003'],
 ['알제리 DZD', '9.41', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['케냐 KES', '9.13', 'N/A', 'N/A', 'N/A', 'N/A', '0.007'],
 ['콜롬비아 COP', '0.31', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['탄자니아 TZS', '0.53', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['네팔 NPR', '9.71', 'N/A', 'N/A', 'N/A', 'N/A', '0.008'],
 ['루마니아 RON', '280.19', 'N/A', 'N/A', 'N/A', 'N/A', '0.219'],
 ['리비아 LYD', '265.31', 'N/A', 'N/A', '267.96', '262.66', '0.208'],
 ['마카오 MOP', '158.19', 'N/A', 'N/A', 'N/A', 'N/A', '0.124'],
 ['미얀마 MMK', '0.61', 'N/A', 'N/A', 'N/A', 'N/A', '0.001'],
 ['에티오피아 ETB', '23.25', 'N/A', 'N/A', 'N/A', 'N/A', '0.018'],
 ['우즈베키스탄 UZS', '0.11', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['캄보디아 KHR', '0.31', 'N/A', 'N/A', 'N/A', 'N/A', '0.000'],
 ['피지 FJD', '579.18', 'N/A', 'N/A', 'N/A', 'N/A', '0.454']]

In [11]:
import pandas as pd

In [12]:
columns = ["통화명", "매매기준율", '현찰(구매)', '현찰(판매)', 
           '송금(보낼때)', '송금(받을때)', '미화환산율']

In [13]:
pd.DataFrame(result, columns=columns).to_csv('test.csv', index=False)

In [14]:
import mod_sql

In [15]:
db = mod_sql.Database('localhost', 'root', 'ubion_test', 3306)

In [16]:
# DB에 table 생성 (naver)
# 필드는 7개 모두 필드의 타입은 문자열 구성
# 통화명 필드는 primary key
sql = """
    create 
    table 
    `naver`(
        `통화명` varchar(16) primary key, 
        `매매기준율` varchar(16), 
        `현찰(구매)` varchar(16), 
        `현찰(판매)` varchar(16), 
        `송금(보낼때)` varchar(16), 
        `송금(받을때)` varchar(16), 
        `미화환산율` varchar(16)
    )
"""
db.sql_query(sql)

'Query OK'

In [17]:
# naver라는 이름으로 생성한 테이블에 데이터 삽입
# 데이터를 삽입하는 insert문을 작성
sql = """
    insert 
    into 
    naver 
    values (
        '통화', 
        '1', 
        '2', 
        '3', 
        '4', 
        '5', 
        '6'
    )
"""
db.sql_query(sql)

'Query OK'

In [18]:
sql = """
    insert 
    into 
    naver
    values 
    (%s, %s, %s, %s, %s, %s, %s)
"""

values = [1,2,3,4,5,6,7]

db.sql_query(sql, values)

'Query OK'

In [19]:
sql = """
    delete 
    from 
    `naver`
"""

db.sql_query(sql)

'Query OK'

In [20]:
result[0]

['미국 USD', '1,277.00', '1,299.34', '1,254.66', '1,289.50', '1,264.50', '1.000']

In [21]:
# result변수의 데이터를 naver 테이블 삽입
sql = """
    insert 
    into 
    `naver` 
    values (
        %s, %s, %s, %s, %s, %s, %s
    )
"""

for i in range(len(result)):
    values = result[i]
    db.sql_query(sql, values)

In [22]:
sql = """
    select * from `naver`
"""
db.sql_query(sql)

              통화명     매매기준율    현찰(구매)    현찰(판매)   송금(보낼때)   송금(받을때)  미화환산율
0   남아프리카 공화국 ZAR     69.66     75.23     64.09     70.49     68.83  0.055
1          네팔 NPR      9.71       N/A       N/A       N/A       N/A  0.008
2        노르웨이 NOK    121.42    124.39    118.45    122.63    120.21  0.095
3        뉴질랜드 NZD    791.87    807.46    776.28    799.78    783.96  0.620
4          대만 TWD     41.56     47.00     37.41       N/A       N/A  0.033
5         덴마크 DKK    186.58    191.15    182.01    188.44    184.72  0.146
6         러시아 RUB     15.26     16.70     12.59     15.79     14.73  0.012
7        루마니아 RON    280.19       N/A       N/A       N/A       N/A  0.219
8         리비아 LYD    265.31       N/A       N/A    267.96    262.66  0.208
9         마카오 MOP    158.19       N/A       N/A       N/A       N/A  0.124
10      말레이시아 MYR    276.05    296.47    255.63       N/A    273.29  0.216
11        멕시코 MXN     74.39     82.20     66.58     75.13     73.65  0.058
12         몽골 MNT      0.37       N/A       N/A       N/A       N/A  0.000
13         미국 USD  1,277.00  1,299.34  1,254.66  1,289.50  1,264.50  1.000
14        미얀마 MMK      0.61       N/A       N/A       N/A       N/A  0.001
15        바레인 BHD  3,387.27  3,604.05  3,116.29  3,421.14  3,353.40  2.653
16      방글라데시 BDT     11.80       N/A       N/A       N/A       N/A  0.009
17    베트남 VND 100      5.43      6.07      4.79      5.48      5.38  0.004
18        브라질 BRL    264.85    291.86    238.37       N/A    261.68  0.207
19       브루나이 BND    953.87    992.02    896.64       N/A       N/A  0.747
20    사우디아라비아 SAR    340.52    361.97    317.03    343.92    337.12  0.267
21       스리랑카 LKR      4.17       N/A       N/A       N/A       N/A  0.003
22        스웨덴 SEK    119.87    122.80    116.94    121.06    118.68  0.094
23        스위스 CHF  1,423.79  1,451.83  1,395.75  1,438.02  1,409.56  1.115
24       싱가포르 SGD    953.87    972.85    934.89    963.40    944.34  0.747
25     아랍에미리트 AED    347.68    366.80    323.70    351.15    344.21  0.272
26        알제리 DZD      9.41       N/A       N/A       N/A       N/A  0.007
27      에티오피아 ETB     23.25       N/A       N/A       N/A       N/A  0.018
28         영국 GBP  1,621.15  1,653.08  1,589.22  1,637.36  1,604.94  1.270
29         오만 OMR  3,316.88  3,549.06  3,084.70       N/A       N/A  2.597
30        요르단 JOD  1,800.11  1,960.31  1,656.11       N/A       N/A  1.410
31     우즈베키스탄 UZS      0.11       N/A       N/A       N/A       N/A  0.000
32       유럽연합 EUR  1,390.27  1,417.93  1,362.61  1,404.17  1,376.37  1.089
33       이스라엘 ILS    358.36    394.19    329.70       N/A       N/A  0.281
34        이집트 EGP     41.33       N/A       N/A       N/A       N/A  0.032
35         인도 INR     15.57       N/A       N/A       N/A       N/A  0.012
36  인도네시아 IDR 100      8.56      9.41      7.71      8.64      8.48  0.007
37  일본 JPY (100엔)    908.54    924.43    892.65    917.44    899.64  0.712
38         중국 CNY    178.79    187.72    169.86    180.57    177.01  0.140
39         체코 CZK     58.48     63.45     53.22     59.12     57.84  0.046
40         칠레 CLP      1.60      1.76      1.44       N/A       N/A  0.001
41      카자흐스탄 KZT      2.82       N/A       N/A       N/A       N/A  0.002
42        카타르 QAR    350.32       N/A       N/A       N/A       N/A  0.274
43       캄보디아 KHR      0.31       N/A       N/A       N/A       N/A  0.000
44        캐나다 CAD    960.29    979.20    941.38    969.89    950.69  0.752
45         케냐 KES      9.13       N/A       N/A       N/A       N/A  0.007
46       콜롬비아 COP      0.31       N/A       N/A       N/A       N/A  0.000
47       쿠웨이트 KWD  4,159.47  4,429.83  3,826.72  4,201.06  4,117.88  3.257
48       탄자니아 TZS      0.53       N/A       N/A       N/A       N/A  0.000
49         태국 THB     36.78     38.61     34.58     37.14     36.42  0.029
50       튀르키예 TRY     53.96       N/A       N/A     54.55     53.37  0.042
51       파키스탄 PKR      4.45       N/A       N/A       N/A       N/A  0.004
52        폴란드 PLN    311.32    336.22    286.42    314.74    307.90  0.244
53         피지 FJD    579.18       N/A       N/A       N/A       N/A  0.454
54        필리핀 PHP     22.86     25.14     20.99     23.08     22.64  0.018
55        헝가리 HUF      3.71      4.05      3.42      3.75      3.67  0.003
56         호주 AUD    873.02    890.21    855.83    881.75    864.29  0.684
57         홍콩 HKD    163.22    166.43    160.01    164.85    161.59  0.128

In [ ]:
# result변수의 데이터를 naver 테이블 삽입
sql = """
    insert 
    into 
    `naver2` 
    (`통화명`, `매매기준율`, `현찰(구매)`, 
    `현찰(판매)`, `송금(보낼때)`, `송금(받을때)`, `미화환산율`)
    values (
        %s, %s, %s, %s, %s, %s, %s
    )
"""

for i in result:
    db.sql_query(sql, i)